spring.datasource.username=root
spring.datasource.password=Mysql@123

spring.security.oauth2.client.registration.google.client-id=867455788814-57k43khv90vt59hpfe34rje34e9ho8c8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
